### ISSUE TITLE
Salesforce(instance, session_id) complains on subsequent query call

### ISSUE THREAD

**Issue by tggagne** [simple-salesforce/simple-salesforce#151]
When I use the instance URL and session to login a subsequent query doesn't work, but if I login using username/password/token it does work.

But of course, I want to re-use the token I already have from another process and skip having to use a security-token if I can.

I've a curl script that logs-in to Salesforce like...

```
curl https://$2.salesforce.com/services/oauth2/token \
	-d "grant_type=password" \
	--data-urlencode "client_id=$CLIENTID" \
	--data-urlencode "client_secret=$CLIENTSECRET" \
	--data-urlencode "username=$1" \
	--data-urlencode "password=$SFPASS" \
	-o login.answer
```
The resulting file (login.answer) has an instance url and session returned by Salesforce.

```
cat login.answer
{"access_token":"supersecretjumbleofcharacters","instance_url":"https://cs52.salesforce.com","id":"https://test.salesforce.com/id/00D5B000000DHvWUAW/00516000007A0qfAAC","token_type":"Bearer","issued_at":"1489712412567","signature":"D5BsLMBWMqVW5/bASafLq4CPcsS4TcgSmTgMqTgptqc="}
```
Using simple-salesforce, if I try new'ing up an instance of Salesforce as in...
```
jsonString = open('./login.answer').read()
sessionInfo = json.loads(jsonString)

sf = Salesforce(instance = sessionInfo['instance_url'], session_id = sessionInfo['access_token'])
```
I don't get an error at that line, but I will as soon as I try a query...
`result = sf.query('select id, name from entitlement')`

Which then complains:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

If I'm missing something obvious, please let me know.  I haven't touched Python in > 10 years--maybe longer.

**Comment by tggagne** [comment]
Perhaps, the more telling error was the last one printed...

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    result = sf.query("select name from recordType where sobjecttype='account'")
  File "/usr/local/lib/python3.6/site-packages/simple_salesforce/api.py", line 334, in query
    result = self._call_salesforce('GET', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/simple_salesforce/api.py", line 430, in _call_salesforce
    method, url, headers=self.headers, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //cs52.salesforce.com/services/data/v29.0/query/?q=select+name+from+recordType+where+sobjecttype%3D%27account%27 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10d09a4a8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```

**Comment by tggagne** [comment]
Figured it out.

The instance_url parameter must be provided WITHOUT the protocol.

The following code works great.
```
import json
from pprint import pprint
from simple_salesforce import Salesforce

jsonString = open('./login.answer').read()
sessionInfo = json.loads(jsonString)

sf = Salesforce(instance = sessionInfo['instance_url'].replace('https://',''), session_id = sessionInfo['access_token'])

result = sf.query("select id, name from recordType where sobjecttype='account'")

for row in result['records']:
	print(row['Name'])
```
