### ISSUE TITLE
Compatability issue with cryptography 1.9

### ISSUE THREAD

**Issue by tuckeryatesjvion** [simple-salesforce/simple-salesforce#168]
When creating a new Salesforce object with cryptography 1.9, I encounter the following error:

`Traceback (most recent call last):
  File "sftest.py", line 1, in <module>
    from simple_salesforce import Salesforce
  File "/home/revegis/.local/lib/python3.5/site-packages/simple_salesforce/__init__.py", line 4, in <module>
    from simple_salesforce.api import (
  File "/home/revegis/.local/lib/python3.5/site-packages/simple_salesforce/api.py", line 10, in <module>
    import requests
  File "/home/revegis/.local/lib/python3.5/site-packages/requests/__init__.py", line 78, in <module>
    from urllib3.contrib import pyopenssl
  File "/home/revegis/.local/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/home/revegis/.local/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/revegis/.local/lib/python3.5/site-packages/OpenSSL/SSL.py", line 113, in <module>
    if _lib.Cryptography_HAS_SSL_ST:
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_SSL_ST'
`
I downgraded my cryptography packaged to 1.8.2, and the issue has been resolved.

**Comment by skamensky** [comment]
You can use a virtual environment if you're using multiple packages that have difference version dependencies.
