### ISSUE TITLE
Platform event names

### ISSUE THREAD

**Issue by hzyadeh** [simple-salesforce/simple-salesforce#202]
Hi,
I am using simple-salesforce to inset data to platform event object via REST API. Unfortunately the call fails because the SObject does not existing which it is not true!!
When I use another Object it works fine!!

Any Idea??
Thanks

Traceback (most recent call last):
  File "IoT_REST_API.py", line 25, in <module>
    sf.Connected_Car__e.create ({"AssetID__c" : "HZRASP1" , "Temperature__c" : 21})
  File "/usr/local/lib/python2.7/dist-packages/simple_salesforce-0.72.2-py2.7.egg/simple_salesforce/api.py", line 583, in create
    data=json.dumps(data), headers=headers
  File "/usr/local/lib/python2.7/dist-packages/simple_salesforce-0.72.2-py2.7.egg/simple_salesforce/api.py", line 711, in _call_salesforce
    _exception_handler(result, self.name)
  File "/usr/local/lib/python2.7/dist-packages/simple_salesforce-0.72.2-py2.7.egg/simple_salesforce/api.py", line 792, in _exception_handler
    raise exc_cls(result.url, result.status_code, name, response_content)
simple_salesforce.api.SalesforceResourceNotFound: Resource Connected_Car__e Not Found. Response content: [ {
  "errorCode" : "NOT_FOUND",
  "message" : "The requested resource does not exist"
} ]

**Comment by skamensky** [comment]
Check the schema for the correct object name. If it's a custom object it will have an '__c' appended to the end of the object name. You're missing at least that (unless you mean to put a 'c' instead of the 'e' in 'Connected_Car__e.'

**Comment by andscoop** [comment]
@hzyadeh Feel free to re-open if issue is still or if you have more questions
