### ISSUE TITLE
Unable to parse the JSON from ApexLog

### ISSUE THREAD

**Issue by htiple** [simple-salesforce/simple-salesforce#247]
Hi,

I am observing the below issue when trying to get the Body of ApexLog.

The path to restful is sent like this : sobjects/ApexLog/07L4100000R430oEAB/Body/
The above Rest URL works with workbench UI
 
Below is the error:

Traceback (most recent call last):
  File "D:\sfdocs\ToolingAPI\sf\DownloadLogs.py", line 41, in <module>
    dlog=sf.restful('sobjects/ApexLog/'+Logid+'/Body', params=None)
  File "C:\Python27\lib\site-packages\simple_salesforce\api.py", line 289, in restful
    json_result = result.json(object_pairs_hook=OrderedDict)
  File "C:\Python27\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python27\lib\json\__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\Python27\lib\json\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 6 - line 64 column 1 (char 5 - 3003)

**Comment by htiple** [comment]
Code changes needed in api.py. Creating PR for the same.
