### ISSUE TITLE
URI Too Long

### ISSUE THREAD

**Issue by sid88in** [simple-salesforce/simple-salesforce#271]
Any help with this?
```
[2018-09-25 22:32:54,818] {{models.py:1736}} ERROR - Error Code 414. Response content: <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/models.py", line 1633, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/airflow/plugins/salesforce_operator.py", line 147, in execute
    query = hook.get_object_from_salesforce(self.object, self.fields)
  File "/usr/local/lib/python3.6/site-packages/airflow/contrib/hooks/salesforce_hook.py", line 157, in get_object_from_salesforce
    return self.make_query(query)
  File "/usr/local/lib/python3.6/site-packages/airflow/contrib/hooks/salesforce_hook.py", line 102, in make_query
    query = self.sf.query_all(query)
  File "/usr/local/lib/python3.6/site-packages/simple_salesforce/api.py", line 430, in query_all
    result = self.query(query, include_deleted=include_deleted, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/simple_salesforce/api.py", line 375, in query
    params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/simple_salesforce/api.py", line 478, in _call_salesforce
    exception_handler(result, name=name)
  File "/usr/local/lib/python3.6/site-packages/simple_salesforce/util.py", line 61, in exception_handler
    raise exc_cls(result.url, result.status_code, name, response_content)
simple_salesforce.exceptions.SalesforceGeneralError: Error Code 414. Response content: <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>
```

**Comment by andscoop** [comment]
@sid88in Could you provide some example code or the URI you are providing. That 414 is a response from the server itself, which is rather unusual, so the uri and endpoint is likely malformed.

**Comment by sid88in** [comment]
@andscoop I see this in the log:

```
[2018-09-25 22:32:54,621] {{logging_mixin.py:95}} INFO - [2018-09-25 22:32:54,621] {{salesforce_operator.py:137}} INFO - Making request for721 fields from Account

[2018-09-25 22:32:54,621] {{logging_mixin.py:95}} INFO - [2018-09-25 22:32:54,621] {{salesforce_hook.py:155}} INFO - Making query to Salesforce: SELECT Id,IsDel ... _c FROM Account
```

**Comment by sid88in** [comment]
I am using this operator https://github.com/airflow-plugins/salesforce_plugin/blob/master/operators/salesforce_to_s3_operator.py

**Comment by sid88in** [comment]
@andscoop just crosschecked - that is infact the issue (large fieldset). Looks like by default we are querying the entire set of 721 fields but when I reduce this set to like 50 - the code works! 

There is probably some limit from 0 to 721 where this code breaks i.e length of URI issue. 

quick dirty code to test this issue:

```
import pandas as pd
import numpy as np
import sys
import json
from simple_salesforce import Salesforce

sf=Salesforce(username='xxx', password='xxx', security_token='')
desc = json.loads(json.dumps(sf.__getattr__('Account').describe()))

fields = [f['name'] for f in desc['fields']]

def _build_field_list(fields):
    # join all of the fields in a comma separated list
    return ",".join(fields)

def get_object_from_salesforce(obj, fields):
    fields = fields[0:5]
    print(fields)
    field_string = _build_field_list(fields)

    query = "SELECT {0} FROM {1}".format(field_string, obj)
    print(
        "Making query to Salesforce: %s",
        query if len(query) < 30 else " ... ".join([query[:15], query[-15:]])
    )

    print(sf.query_all(query))

get_object_from_salesforce('Account', fields)
```

**Comment by Frissian-Viales** [comment]
Hi fella, 

Just got the same error on my end. I am making a query that has about 500 attributes. Did you find out what the limit was? and how to overcome it?
