### ISSUE TITLE
Bulk API will not return records from a subtable of a custom object

### ISSUE THREAD

**Issue by danwagnerco** [simple-salesforce/simple-salesforce#308]
I am using the bulk API to return records programmatically.

In this case I want to get records from `Program_Budget__c`, which is a subtable of custom object `Program__c`:

```
# budget_downloader.py
from simple_salesforce import Salesforce, SFType, SalesforceLogin

my_sf_email = os.environ["SALESFORCE_EMAIL"]
my_sf_password = os.environ["SALESFORCE_PASSWORD"]
my_sf_token = os.environ["SALESFORCE_TOKEN"]

session_id, instance = SalesforceLogin(username=my_sf_email,
                                       password=my_sf_password,
                                       security_token=my_sf_token,
                                       sandbox=False)
sf = Salesforce(instance=instance, session_id=session_id)

my_query = "SELECT Id FROM Program_Budget__c"
response = sf.bulk.Program__c.query(my_query)
```
then:

```
> python budget_downloader.py
Traceback (most recent call last):
 File "budget_downloader.py", line 62, in <module>
   response = sf.bulk.Program__c.query(program_query_budget)
 File "C:\github\salesforce-data-collector\lib\site-packages\simple_salesforce\bulk.py", line 237, in query
   operation='query', data=data)
 File "C:\github\salesforce-data-collector\lib\site-packages\simple_salesforce\bulk.py", line 198, in _bulk_operation
   operation=operation)
 File "C:\github\salesforce-data-collector\lib\site-packages\simple_salesforce\bulk.py", line 157, in _get_batch_results
   url_query_results = "{}{}{}".format(url, '/', result.json()[0])
IndexError: list index out of range
```

From Salesforce Workbench, though, this returns records:

```
Select Id FROM Program_Budget__c
```

Same with the Dev Console:

```
Select Id FROM Program_Budget__c
```

returns records.

Can someone help me troubleshoot why this query works in the Dev Console and Workbench but not via `simple_salesforce`?

**Comment by danwagnerco** [comment]
Apologies, this is a user error on my part:

```
response = sf.bulk.Program__c.query(my_query)
```

needs to be:

```
response = sf.bulk.Program_Budget__c.query(my_query)
```

Thank you for allowing me to "rubber duck" the solution here 😂
