### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by bmuniswamy** [simple-salesforce/simple-salesforce#327]
Hi,

    I have created a new python file and am doing a restful call and calling the PATCH method.  While doing the call I am passing in the metadata that needs to be updated.  When I use the command line to execute the file , it makes the necessary updates in the salesforce org but I get the below error .

`raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Here is the restful call

`path = "tooling/sobjects/FlowDefinition/"
            data = {"Metadata": 
                        {
                            "activeVersionNumber": "2"
                        }
                    }

            result = self.sf.restful(
                                path, 
                                method="PATCH", 
                                json=data
                                )`

When I run the same in work bench it works but it return 204 No Content message.  Anyone seen this issue before and if yes can you please let me know how I can get rid of the error

**Comment by thommor** [comment]
Can you provide a full stacktrace of this error and I will look into it

**Comment by metadaddy** [comment]
Replication with stacktrace:

```
pat-macbookpro:~ pat$ python3
Python 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from simple_salesforce import Salesforce
>>> sf = Salesforce(username='user@example.com', password='password', security_token='SECURITYTOKEN')
>>> 
>>> # I encountered the issue working with Einstein Analytics datasets, but Contact provides an easier replication :-)
>>> ret = sf.Contact.create({'LastName':'Smith','Email':'example@example.com'})
>>> 
>>> ret = sf.restful(f'sobjects/Contact/{ret["id"]}', method='DELETE')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/simple_salesforce/api.py", line 307, in restful
    json_result = result.json(object_pairs_hook=OrderedDict)
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Issue is that `restful` calls `result.json`, which errors on empty input. `restful` should either check the length of `result.content` or check `result.status_code` against 204.

See also pull request https://github.com/simple-salesforce/simple-salesforce/pull/258
