### ISSUE TITLE
latest version 0.74.4 with batch size per job is causing update call to recursively restart script

### ISSUE THREAD

**Issue by Timothy-Kornish** [simple-salesforce/simple-salesforce#335]
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
-------------- -----------------------------------------------------------------------
--------------the below line is edited to remove personal info ------------------
  File "C:\Users\{path_to_script}\Python\UPDATE_Part_Numbers.py", line 192, in <module>
    results = source_sf.bulk.Product2.update(data, update_batch_size)
--------------------------------------------------------------------------------------
  File "C:\Python36\lib\site-packages\simple_salesforce\bulk.py", line 280, in update
    batchsize=batchsize)
  File "C:\Python36\lib\site-packages\simple_salesforce\bulk.py", line 208, in _bulk_operation
    pool = Pool()
  File "C:\Python36\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Python36\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\Python36\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
----------------------------------------------------------------------
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```
-----------------------------------------------------------------

After the last line above the script then re fires with double the previous calls to set up a connection to Salesforce.

and spamming ctrl+C to exit will not kill the script,  only closing the command prompt will kill the script from continuously re-firing

**Comment by Timothy-Kornish** [comment]
didn't realise this a markdown

**Comment by Mer-xes** [comment]
If you call if __name__ == '__main__': before your bulk call that will solve that issue. However, it looks like the multi-batching caused some unintended issues so I am going to revert my update and roll it back to 74.3

**Comment by Mer-xes** [comment]
I've removed multiprocessing batches until there is a fix in place for Windows systems since it does not support multiprocessing unless the bulk operation is wrapped in if __name__ == '__main__'
