### ISSUE TITLE
How to retrieve a File uploaded to Files and added to Contracts..

### ISSUE THREAD

**Issue by venkatpolisetti** [simple-salesforce/simple-salesforce#373]
Hi all,

I have the following python code using ssimple-salesforce module:

```
def get_email_template(sf, agreement_id):
    email_templates = sf.query(f"""
            SELECT VersionData, Title, PathOnClient
            FROM ContentVersion
            WHERE FirstPublishLocationId = '{agreement_id}'
            AND pathonclient = 'email_template.html'
    """)['records']

    if len(email_templates) != 0:
        return base64.b64decode(email_templates[0]['VersionData'])
    return None

# end get_email_template

```
I am getting the following error:
```
Traceback (most recent call last):
  File "c:\code\Python\social\social_messaging.py", line 293, in <module>
    email_template = get_email_template(sf, agreement_id)
  File "c:\code\Python\social\social_messaging.py", line 113, in get_email_template
    return base64.b64decode(email_templates[0]['VersionData'])
  File "C:\ProgramData\Anaconda3\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

I must be doing some thing wrong with the base64decode which I am not sure. 

Any help is greatly appreciated.
Thanks,

**Comment by venkatpolisetti** [comment]
Figured out, here is a solution if any  one looking for it:

```
def get_email_template(sf, agreement_id):

    email_templates = sf.query(f"""
            SELECT VersionData, Title, PathOnClient
            FROM ContentVersion
            WHERE FirstPublishLocationId = '{agreement_id}'
            AND pathonclient = 'email_template.html'
    """)['records']

    if len(email_templates) != 0:
        url = f"https://{sf.sf_instance}{email_templates[0]['VersionData']}"

        response = requests.get(url, headers={"Authorization": "OAuth " + sf.session_id,
                                            "Content-Type": "application/octet-stream"})
        if response.ok:
            return(bytes.decode(response.content))
        else:
            social_log.debug(f"Couldn't download %s" % url)
    return None

# end get_email_template

```
