### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by ckoppelman** [simple-salesforce/simple-salesforce#382]
If I pass in a bad SOQL query, I want to get a meaningful error.  Right now, it just fails like this:

```python
session.bulk.Contact.query('SELECT ASDFASfgsds FROM Contact')
```

```
Traceback (most recent call last):
  File "$PYTHON_PATH/site-packages/simple_salesforce/bulk.py", line 235, in query
    operation='query', data=data)
  File "$PYTHON_PATH/site-packages/simple_salesforce/bulk.py", line 196, in _bulk_operation
    operation=operation)
  File "$PYTHON_PATH/site-packages/simple_salesforce/bulk.py", line 155, in _get_batch_results
    url_query_results = "{}{}{}".format(url, '/', result.json()[0])
IndexError: list index out of range
```

**Comment by rectalogic** [comment]
As of version 1.11.2 I just get no results back in case of a failure, and the job is in state `Failed` in the Bulk Data Load Jobs list.
```pycon
>>> session.bulk.Contact.query('SELECT ASDFASfgsds FROM Contact')
[]
```
The State Message in the bulk jobs list is
```
InvalidBatch : Failed to process query: INVALID_FIELD:  SELECT ASDFASfgsds FROM Contact        ^ ERROR at Row:1:Column:8 No such column 'ASDFASfgsds' on entity 'Contact'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
```

We really need a way to distinguish failure from simply "no results"
