### ISSUE TITLE
Bulk data request error - requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### ISSUE THREAD

**Issue by AdamYounglovesSleeping** [simple-salesforce/simple-salesforce#449]
I've encountered this error multiple times and it happens randomly at simple_salesforce\util.py", line 72, in call_salesforce
    result = session.request(method, url, headers=headers, **kwargs)

Any help would be much appreciated!

**Comment by aloutfi** [comment]
We have also been running into this issue intermittently within our production and sandbox environments. They have occurred infrequently over the past few years but seem to have picked back up on the first week of February.

The syncing of data between from Salesforce to our environment will fail and then execute correctly on the next sync. Here is the full stack trace:

```
[<datetime>] ERROR in salesforce: Salesforce sync failed. Retry #0, Message: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/venv/lib/python3.8/site-packages/raven/breadcrumbs.py", line 390, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/venv/lib/python3.8/site-packages/raven/breadcrumbs.py", line 390, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/src/<redacted>/salesforce.py", line 52, in sync_salesforce
    salesforce.sync_from_salesforce(sf_client, models.Kit)
  File "/venv/src/<redacted>/salesforce.py", line 167, in sync_from_salesforce
    sf_models = sf_obj.updated(from_ts, to_ts)
  File "/venv/lib/python3.8/site-packages/simple_salesforce/api.py", line 753, in updated
    result = self._call_salesforce(method='GET', url=url, headers=headers)
  File "/venv/lib/python3.8/site-packages/simple_salesforce/api.py", line 768, in _call_salesforce
    result = self.session.request(method, url, headers=headers, **kwargs)
  File "/venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/venv/lib/python3.8/site-packages/raven/breadcrumbs.py", line 341, in send
    resp = real_send(self, request, *args, **kwargs)
  File "/venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/venv/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

```

The next time the sync runs, the retrieval of data GET request call is proceeded by `<datetime> - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): <SF Name>.my.salesforce.com:443`
under normal operating conditions, urllib3 does not output this message.

Packages 
```
urllib3==1.25.10 
simple-salesforce==1.0.0
```

**Comment by alphacr** [comment]
Hi, I was wondering if you guys had any luck solving this problem? I encountered the same issue on my production pipeline

**Comment by cstufts-ca** [comment]
Very interested if anyone has had any luck with this type of failure.
There has to be a way to try/catch this and simply reconnect your session and then re-try your transaction...

**Comment by aloutfi** [comment]
@D1xieFlatline's SA answer is the closest thing I can find that encapsulates the issue.

As the stack trace suggests, the connection has been closed by salesforce. There are a number of reasons this could be. SF does handle a decent amount with good error messages, but I think this might be the catch-all.

For us, this issue was occurring because we were exceeding the number of Salesforce API requests that are allowed for our plan. See [API Request Limits and Allocations](https://developer.salesforce.com/docs/atlas.en-us.220.0.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_api.htm).

**Comment by flaviavecchiocattivi** [comment]
Did everyone resolve this issue or find a working solution? 
We're currently facing it too in our SF production env when we use the parallel processing with concurrency value greater than 1. 
I've tried to implement the `sleep()` function however it's still not working.

**Comment by podstu** [comment]
I am also encountering the same issue.

`requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

In the past we added a `time.sleep(0.1)` and this helped but this time no.
We are using API version 54
Any other advice?
How to learn what SF did not like in the request?
