### ISSUE TITLE
Is creating custom fields using the Metadata API supported?

### ISSUE THREAD

**Issue by jolson629** [simple-salesforce/simple-salesforce#542]
I tried the following...not sure if it is supported or not because it is not explicitly spelled out in the simple-salesforce docs, but is supported in the Salesforce Metadata API docs:

```
           fields = []
            fields.append( 
                mdapi.CustomField( 
                        type = mdapi.FieldType("Text"),
                        fullName = f"""{salesforce_custom_object_name}.sample__c"""
                    )
            )

            custom_object = mdapi.CustomObject(
                    fullName = salesforce_custom_object_name,
                    nameField = mdapi.CustomField(
                        label = "CustomId",
                        type = mdapi.FieldType("AutoNumber")
                    ),
                    fields = fields,
                    sharingModel = mdapi.SharingModel("ReadWrite")
            )
            
            print(f"""Creating Salesforce object: {salesforce_custom_object_name}""")
            mdapi.CustomObject.create(custom_object)
```

Results in: 

```
Traceback (most recent call last):
  File "salesforce_loader.py", line 185, in <module>
    salesforce_custom_object_name, sqlite3_cols = build_salesforce_objects(manifest[key], execute_in_salesforce = True)
  File "salesforce_loader.py", line 109, in build_salesforce_objects
    mdapi.CustomObject.create(custom_object)
  File "/home/ubuntu/git/np-portal/.venv/lib/python3.8/site-packages/simple_salesforce/metadata.py", line 77, in create
    response = self._service.createMetadata(metadata, _soapheaders=[
  File "/home/ubuntu/git/np-portal/.venv/lib/python3.8/site-packages/zeep/proxy.py", line 46, in __call__
    return self._proxy._binding.send(
  File "/home/ubuntu/git/np-portal/.venv/lib/python3.8/site-packages/zeep/wsdl/bindings/soap.py", line 135, in send
    return self.process_reply(client, operation_obj, response)
  File "/home/ubuntu/git/np-portal/.venv/lib/python3.8/site-packages/zeep/wsdl/bindings/soap.py", line 229, in process_reply
    return self.process_error(doc, operation)
  File "/home/ubuntu/git/np-portal/.venv/lib/python3.8/site-packages/zeep/wsdl/bindings/soap.py", line 329, in process_error
    raise Fault(
zeep.exceptions.Fault: UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 362095976-17907 (-1670715289)
```

Am I doing something wrong, or is this not supported? Example for adding a custom field in the project README is to use the tooling API....

**Comment by drewipson** [comment]
Commenting to follow this thread as I am curious about accomplishing a similar objective creating custom fields. I'm exploring this functionality as well and will report back if I find anything.

**Comment by jon-wobken** [comment]
High level without testing anything I think you are missing some required fields when creating the text field (length,label) but I’ll try it out in one of my dev orgs with week and get back to you.

**Comment by drewipson** [comment]
@jolson629 I was able to create custom fields with a few modifications to your code:

Here is the list of field objects: 
```
fields = []
fields.append( 
    mdapi.CustomField( 
            type = mdapi.FieldType("Text"),
            fullName = "Test__c",
            label="Test",
            length="255",
            externalId=False,
            description="Test text field.",
            required=False,
            unique=False
        )
)
```

I used this documentation as an example to follow to recreate the XML configs shown below: 
```
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata">
    <fields>
        <fullName>MyCustomAccountField__c</fullName>
        <description>A custom field on the Account standard object.</description>
        <externalId>false</externalId>
        <inlineHelpText>Some help text.</inlineHelpText>
        <label>MyCustomAccountField</label>
        <length>100</length>
        <required>false</required>
        <trackFeedHistory>false</trackFeedHistory>
        <trackHistory>false</trackHistory>
        <type>Text</type>
        <unique>false</unique>
    </fields>
    <fields>
        <fullName>Phone</fullName>
        <trackFeedHistory>false</trackFeedHistory>
        <trackHistory>true</trackHistory>
    </fields>
</CustomObject>
```
You can use this link [here](urhttps://developer.salesforce.com/docs/atlas.en-us.234.0.api_meta.meta/api_meta/customfield.html)

Here is the custom_object:
```
custom_object = mdapi.CustomObject(
    fullName = "TestObject__c",
    label = "Test Object",
    pluralLabel = "Test Objects",
    nameField = mdapi.CustomField(
        label = "Title",
        type = mdapi.FieldType("Text")
    ),
    fields=fields,
    deploymentStatus = mdapi.DeploymentStatus("Deployed"),
    sharingModel = mdapi.SharingModel("Read")
)

mdapi.CustomObject.create(custom_object)
```

Here is what it looks like in SF.
![Screen Shot 2022-03-24 at 3 40 41 PM](https://user-images.githubusercontent.com/24757991/160014997-c27d2499-c671-4cd5-8772-4699f6d87b68.png)


I would just make sure that you have every field required based on the documentation for the custom field you would like to create before creating the object.
