### ISSUE TITLE
Breaking change in 1.12.0

### ISSUE THREAD

**Issue by hermanmedsleuth** [simple-salesforce/simple-salesforce#557]
We are experiencing a breaking change in the latest release.

A stack trace of the error we are observing, from one of our QA logs, is shown below.

```
Traceback (most recent call last):
File "/var/runtime/urllib3/connection.py", line 174, in _new_conn
conn = connection.create_connection(
File "/var/runtime/urllib3/util/connection.py", line 72, in create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
File "/var/lang/lib/python3.9/socket.py", line 954, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/var/runtime/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/var/runtime/urllib3/connectionpool.py", line 386, in _make_request
self._validate_conn(conn)
File "/var/runtime/urllib3/connectionpool.py", line 1040, in _validate_conn
conn.connect()
File "/var/runtime/urllib3/connection.py", line 358, in connect
self.sock = conn = self._new_conn()
File "/var/runtime/urllib3/connection.py", line 186, in _new_conn
raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3e18c2f7f0>: Failed to establish a new connection: [Errno -2] Name or service not known
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/var/task/./vendored/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/var/runtime/urllib3/connectionpool.py", line 785, in urlopen
retries = retries.increment(
File "/var/runtime/urllib3/util/retry.py", line 592, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='00d8a000000mq7f!ar4aqnejwqivxwyazqgc2n3zxhl9z2.bei5uyy8ib1imnehtutvjixgzky9drsjovr0ecf.bvh6m4sesjmdci.nnn55_0zey', port=443): Max retries exceeded with url: /services/data/v52.0/sobjects/Kidney_Donor__c/xnid__c/transplant.kidney:XNID.2A8AFDX7SIF04IHV0TRLKBR5P (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3e18c2f7f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/var/task/index.py", line 785, in upsertSalesforceSurveyRecord
response = bsurvey.upsert('xnid__c/%s' % (xnid),objrecord)
File "/var/task/./vendored/simple_salesforce/api.py", line 841, in upsert
result = self._call_salesforce(
File "/var/task/./vendored/simple_salesforce/api.py", line 935, in _call_salesforce
result = self.session.request(method, url, headers=headers, **kwargs)
File "/var/task/./vendored/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/var/task/./vendored/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/var/task/./vendored/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='00d8a000000mq7f!ar4aqnejwqivxwyazqgc2n3zxhl9z2.bei5uyy8ib1imnehtutvjixgzky9drsjovr0ecf.bvh6m4sesjmdci.nnn55_0zey', port=443): Max retries exceeded with url: /services/data/v52.0/sobjects/Kidney_Donor__c/xnid__c/transplant.kidney:XNID.2A8AFDX7SIF04IHV0TRLKBR5P (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3e18c2f7f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

Hoping this is helpful.

**Comment by hkajiwara** [comment]
Hi @hermanmedsleuth,
The above log indicates, **_host_** value would be incorrect. That should be the target hostname, not session id. Also, I strongly suggest removing or masking the session id value in the above log from security perspectives.

**Comment by hermanmedsleuth** [comment]
@hkajiwara Thanks for the security tip. I have redacted the sensitive values.

Interestingly this same code set functions as expected when we pin `simple_salesforce` to version 1.11.6. 
ie; the same parameters are passed to `simple_saleforce.SalesforceLogin()`. With version 1.12.0 the error is observed, and with version 1.11.6 no error is observed.

**Comment by hkajiwara** [comment]
Is it possible to share the reproducible code without credential info? I quickly tested v1.20.0 with simple login flow, and it worked to me.

**Comment by jon-wobken** [comment]
I feel like this may have to do with the refresh_session implemented but when testing I did not have this issue. Can you tell me what method you are using to authenticate to salesforce (username password security token/JWT Token/Session Id and Instance/Username Password and Organization ID)?

In addition to @hkajiwara  point if you can provide some code without credentials/identifying information so I can attempt to reproduce and debug.

**Comment by hermanmedsleuth** [comment]
I cannot provide actual code, as it is covered under a NDA. However, the authentication and flow to the error goes like this:
```Python
from simple_salesforce import SalesforceLogin, SalesforceMalformedRequest,SalesforceExpiredSession,SalesforceRefusedRequest,SalesforceResourceNotFound,SFType
# ... undisclosed activity
session_id, instance = SalesforceLogin(domain='test', username=username, password=password, security_token=security_token)
# ... undisclosed activity
sfType = SFType(customObject, session_id, instance)
response = sfType.upsert('xnid__c/%s' % (xnid),objrecord)
# error occurs in upsert invocation
```

**Comment by jon-wobken** [comment]
Following the same general process I can't seem to replicate with 1.12.0. Are you re-using an old session or generating a new session in each call?

Can you provide the version of urllib3 you are using?

`from simple_salesforce import SFType,SalesforceLogin

session_id,instance = SalesforceLogin(
    username=username,password=password,
                security_token=security_token,domain='test')

sfType = SFType('CustomObject__c',sf_instance=instance,session_id=session_id)

response = sfType .upsert('External_Id/record_id',{'CustomField__c':'123'})
print(response)`

**Comment by hermanmedsleuth** [comment]
I'm pretty sure we're re-using a previous session.
```
urllib3==1.26.9
```

**Comment by hkajiwara** [comment]
This issue is caused by [PR#507](https://github.com/simple-salesforce/simple-salesforce/pull/507) for the refresh session feature. As we can reproduce the below code snippet, the session_id is incorrectly set to sf_instance. [PR#507](https://github.com/simple-salesforce/simple-salesforce/pull/507) changed session_id to default arg, thus the args order is changed. A quick solution would be to change the order on the caller side such as `SFType('Contact', <instance url>, sf.session_id)`, but this may break backward compatible between 1.15 and 1.20 later. Also, the [doc](https://pypi.org/project/simple-salesforce/) should be updated as well. I'm not sure the intention of this arg change and if the refresh session itself is needed or not. (Cc @jon-wobken )

```
sf = Salesforce(username=<username>, password=<password>, security_token='')
contact = SFType('Contact', sf.session_id, <instance url>)
print(contact.base_url)
contact.create({'LastName':'Test', 'Email':'test@test.com'})
```

**Comment by hkajiwara** [comment]
FWIW, I've just submitted another [PR](https://github.com/simple-salesforce/simple-salesforce/pull/560) to revert SFType argument order changed by [PR#507](https://github.com/simple-salesforce/simple-salesforce/pull/507).

**Comment by jon-wobken** [comment]
I’ll review and merge Monday then push out a new version.

**Comment by jon-wobken** [comment]
Thanks @hkajiwara for identifying this. 

This has been fixed with #558 (version 1.12.1)

**Comment by hermanmedsleuth** [comment]
Tahnks!
