### ISSUE TITLE
infinite recursion when login returns 401

### ISSUE THREAD

**Issue by chrismaes87** [simple-salesforce/simple-salesforce#569]
since version 1.12.0, simple-salesforce tries to refresh the token each time the login returns 401. 
Whenever the reason for getting a 401 is not token expiry, this generates an infinite recursion here: https://github.com/simple-salesforce/simple-salesforce/blame/master/simple_salesforce/api.py#L584

**Comment by chrismaes87** [comment]
This is caused by https://github.com/simple-salesforce/simple-salesforce/pull/507

**Comment by jon-wobken** [comment]
@chrismaes87  - I can't seem to replicate. Can you provide some more info about how you are getting the infinite recursion and if there is anything in the result message from Salesforce?

**Comment by chrismaes87** [comment]
It turns out the (test) instance we were authenticating against was completely reset, so probably the login didn't exist anymore. That's all I can tell for now. I'll have to check later if I have more details for you.

**Comment by chrismaes87** [comment]
after limiting to salesforce < 1.12, this is the error I get now:

```
Traceback (most recent call last):
,
  File "/source/mobile_expense/main.py", line 86, in <module>
    export_wbs()
,
  File "/source/mobile_expense/main.py", line 39, in export_wbs
    wbs_generator = salesforce_client.get_wbs_to_send()
,
  File "/opt/conda/envs/app/lib/python3.10/site-packages/werkzeug/local.py", line 436, in __get__
    obj = instance._get_current_object()
,
  File "/opt/conda/envs/app/lib/python3.10/site-packages/werkzeug/local.py", line 565, in _get_current_object
    return self.__local()  # type: ignore
,
  File "/opt/conda/envs/app/lib/python3.10/site-packages/lbe_backend/local.py", line 39, in __get_object
    result = self._create_func()
,
  File "/opt/conda/envs/app/lib/python3.10/site-packages/mobile_expense/salesforce_client.py", line 25, in from_config
    return cls(**config['SALESFORCE'])
,
  File "/opt/conda/envs/app/lib/python3.10/site-packages/mobile_expense/salesforce_client.py", line 28, in __init__
    self._salesforce = Salesforce(**kwargs)
,
  File "/opt/conda/envs/app/lib/python3.10/site-packages/simple_salesforce/api.py", line 130, in __init__
    self.session_id, self.sf_instance = SalesforceLogin(
,
  File "/opt/conda/envs/app/lib/python3.10/site-packages/simple_salesforce/login.py", line 200, in SalesforceLogin
    return soap_login(soap_url, login_soap_request_body,
,
  File "/opt/conda/envs/app/lib/python3.10/site-packages/simple_salesforce/login.py", line 214, in soap_login
    raise SalesforceAuthenticationFailed(except_code, except_msg)
,
simple_salesforce.exceptions.SalesforceAuthenticationFailed: INVALID_LOGIN: Invalid username, password, security token; or user locked out.
```

**Comment by hkajiwara** [comment]
_**INVALID_LOGIN**_ would be a generic error code and you could get more details with Login History page as [the doc](https://help.salesforce.com/s/articleView?id=sf.users_login_history.htm&type=5) says.

**Comment by jon-wobken** [comment]
I was able to replicate this when one of my acocunts passwords expired. I will add a fix within the _call_salesforce method to only refresh token when salesforce returns a errorcode of invalid session id

**Comment by smsearcy** [comment]
We encountered the same recursion error on `simple-salesforce==1.12.2` when our password expired.  The update in #594 worked for us.
