### ISSUE TITLE
Unable to login with Security Token

### ISSUE THREAD

**Issue by Superfluxus** [simple-salesforce/simple-salesforce#598]
Hi all,

I've been using this excellent module for about 6 months with no issues at all. Recently however, my login has broken!

I use the security token to login normally like this:

`from simple_salesforce import Salesforce
sf = Salesforce(
username='<>', 
password='<>, 
security_token='<>')`

Recently, I've been running into the same issue as described in Issue #569 , infinite recursion due to a bad login. That issue suggests that the root cause is a 401 caused by an expired password or bad credentials, but I have reset both my password and security token several times with attempts in between and still hit the same error.

Furthermore, on the Salesforce web GUI, under Security Central, I can see my account 'Logging Out' several times a second. No changes have been made to the SF tenant, such as permissions or IP blacklist etc.

Any ideas where I can look to debug this further would be greatly appreciated!

Traceback (most recent call last):
  File "deltatester.py", line 20, in <module>
    query = sf.query("SELECT Subject, Description, Id, CaseNumber From CASE Where Category__c = '<REDACTED>' AND (Status = 'Open' OR Status = 'New') AND Subject LIKE '%<REDACTED>%'")
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\simple_salesforce\api.py", line 456, in query
    params=params, **kwargs)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\simple_salesforce\api.py", line 607, in _call_salesforce
    return self._call_salesforce(method, url, name, **kwargs)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\simple_salesforce\api.py", line 607, in _call_salesforce
    return self._call_salesforce(method, url, name, **kwargs)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\simple_salesforce\api.py", line 607, in _call_salesforce
    return self._call_salesforce(method, url, name, **kwargs)
  [Previous line repeated 480 more times]
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\simple_salesforce\api.py", line 606, in _call_salesforce
    self._refresh_session()
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\simple_salesforce\api.py", line 275, in _refresh_session
    self.session_id, self.sf_instance = self._salesforce_login_partial()
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\simple_salesforce\login.py", line 224, in SalesforceLogin
    login_soap_request_headers, proxies, session)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\simple_salesforce\login.py", line 230, in soap_login
    soap_url, request_body, headers=headers, proxies=proxies)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 499, in send
    timeout=timeout,
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 320, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 214, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\email\parser.py", line 68, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\email\parser.py", line 57, in parse
    feedparser.feed(data)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\email\feedparser.py", line 176, in feed
    self._call_parse()
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\email\feedparser.py", line 180, in _call_parse
    self._parse()
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\email\feedparser.py", line 295, in _parsegen
    if self._cur.get_content_maintype() == 'message':
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\email\message.py", line 594, in get_content_maintype
    ctype = self.get_content_type()
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\email\message.py", line 578, in get_content_type
    value = self.get('content-type', missing)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\email\message.py", line 471, in get
    return self.policy.header_fetch_parse(k, v)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\email\_policybase.py", line 316, in header_fetch_parse
    return self._sanitize_header(name, value)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\email\_policybase.py", line 287, in _sanitize_header
    if _has_surrogates(value):
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\email\utils.py", line 57, in _has_surrogates
    s.encode()
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by lalyndsighart** [comment]
Hi there,

I am getting the exact same error!  Glad to know I am not going crazy.  

I second that is a most excellent package which has worked extremely well for the last couple of months with exactly the same code.

Is there a fix for this? 

Many thanks,
lalynd

**Comment by hkajiwara** [comment]
I'm not sure either or both of the session settings are affecting this issue. What I know about the reproducible condition is that this issue occurs when the password gets expired. This [PR](https://github.com/simple-salesforce/simple-salesforce/pull/594) would be able to fix.

**Comment by Superfluxus** [comment]
Unfortunately I've reset my account's password, and security token, tried again and got the same issue.

I've even tried to authenticate against a brand new, fresh Salesforce account. Still get the same infinite recursion error.

**Comment by hkajiwara** [comment]
Can you set a break point at Line#604 in `api.py` to see the actual error message returned from Salesforce? `result.json()[0]` would show the culprit.

https://github.com/simple-salesforce/simple-salesforce/blob/7be7a2b3d159d3f7735465bd72f61fcaedcb718e/simple_salesforce/api.py#L604

**Comment by Superfluxus** [comment]
Hi @hkajiwara ,

I've put in the Breakpoint like you suggested and the error message read: "INVALID_LOGIN: Invalid username, password, security token; or user locked out."

Embarrassingly enough, I wasn't aware that my security token was automatically reset after a password change, so I had been using the wrong token! Reset the security token manually, updated my scripts, working just like it used to.

Thanks so much for your quick response and the fantastic module, very much appreciated.
