### ISSUE TITLE
To know variables of data fields in Lead

### ISSUE THREAD

**Issue by P-Rainbow** [simple-salesforce/simple-salesforce#609]
Good day, can you please help me with a question on data fields in Lead?

I have these lines running fine in creating new leads in Salesforce.

However, some variables for data fields that I am not able to name them correctly. For example, when I am trying to add "Lead Subject", it gives error:

    "No such column 'LeadSubject' on sobject of type Lead"

How can I find out the correct variables for the data fields? (a lead body include different customized named data fields)

Thank you.

    from simple_salesforce import Salesforce

    sf = Salesforce(username= "user_email"
    ,password= "password"
    ,security_token= "sec_token")

    lead_object = {
    "FirstName": "John",
    "LastName": "Kane",
    "Phone": "321 321 1221",
    "OwnerId": "15_digit_Salesforce_Object_style",
    "Company":"Engineering Co., Ltd",
    "Description":"A good lead Description \n second line \n3rd line.",
    "LeadSubject":"16_Jan"}

    xre = sf.Lead.create(lead_object)
    print (xre['id'])

Full error message as: 

    Traceback (most recent call last):
      File "C:\My Documents\Salesforce.py", line 17, in <module>
        xre = sf.Lead.create(lead_object)
      File "C:\Python38\lib\site-packages\simple_salesforce\api.py", line 790, in create
        result = self._call_salesforce(
      File "C:\Python38\lib\site-packages\simple_salesforce\api.py", line 922, in _call_salesforce
        exception_handler(result, self.name)
      File "C:\Python38\lib\site-packages\simple_salesforce\util.py", line 68, in exception_handler
        raise exc_cls(result.url, result.status_code, name, response_content)
    simple_salesforce.exceptions.SalesforceMalformedRequest: Malformed request https://wss.my.salesforce.com/services/data/v52.0/sobjects/Lead/. Response content: [{'message': "No such column 'LeadSubject' on sobject of type Lead", 'errorCode': 'INVALID_FIELD'}]

**Comment by P-Rainbow** [comment]
> 

@hkajiwara this is absolutely amazing! thank you for the help and guidance!
