### ISSUE TITLE
Add python 3.12 support

### ISSUE THREAD

**Issue by algot** [simple-salesforce/simple-salesforce#690]
simple-salesforce cannot be installed with python 3.12 because of pendulum dependency.

```
ChefBuildError
  
    Backend subprocess exited when trying to invoke build_wheel
  
    Traceback (most recent call last):
      File "C:\Users\user\AppData\Local\Temp\tmp581kvpjx\pendulum-2.1.2\build.py", line 5, in <module>
        from distutils.command.build_ext import build_ext
    ModuleNotFoundError: No module named 'distutils'
    Traceback (most recent call last):
      File "C:\Users\user\AppData\Roaming\pypoetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
        main()
      File "C:\Users\user\AppData\Roaming\pypoetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 335, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\user\AppData\Roaming\pypoetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
        return _build_backend().build_wheel(wheel_directory, config_settings,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\user\AppData\Local\Temp\tmpzumkmv5d\.venv\Lib\site-packages\poetry\core\masonry\api.py", line 57, in build_wheel
        return WheelBuilder.make_in(
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\user\AppData\Local\Temp\tmpzumkmv5d\.venv\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 87, in make_in
        wb.build(target_dir=directory)
      File "C:\Users\user\AppData\Local\Temp\tmpzumkmv5d\.venv\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 122, in build
        self._build(zip_file)
      File "C:\Users\user\AppData\Local\Temp\tmpzumkmv5d\.venv\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 171, in _build
        self._run_build_script(self._package.build_script)
      File "C:\Users\user\AppData\Local\Temp\tmpzumkmv5d\.venv\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 231, in _run_build_script
        subprocess.check_call([self.executable.as_posix(), build_script])
      File "C:\Program Files\Python312\Lib\subprocess.py", line 413, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:/Users/user/AppData/Local/Temp/tmpzumkmv5d/.venv/Scripts/python.exe', 'build.py']' returned non-zero exit status 1.
  
  
    at ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\poetry\installation\chef.py:147 in _prepare
        143│
        144│                 error = ChefBuildError("\n\n".join(message_parts))
        145│
        146│             if error is not None:
      → 147│                 raise error from None
        148│
        149│             return path
        150│
        151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
  
  Note: This error originates from the build backend, and is likely not a problem with poetry but with pendulum (2.1.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pendulum (==2.1.2)"'.
```

**Comment by BillingtonRWG** [comment]
Similar issue in deploying to Python in Azure at Version 3.10.  After a long couple hours, setting the Azure Python Function environment to 3.9 resolved the issue entirely.   The statement causing error was in Bulk2.py  and was "import pendulum as DateTime"  efforts to resolve it with import pendulum.datetime as Datetime were ineffective.

**Comment by rsyring** [comment]
The root problem is that pendulum needs native wheels but it hasn't been released since Jul 2020 so there aren't any wheels for later than Python 3.9.

https://pypi.org/project/pendulum/#files

**Comment by algot** [comment]
After recent pendulum release simple-salesforce can be installed successfully with python 3.12.
So issue can be closed
