### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by oov-too** [simple-salesforce/simple-salesforce#709]
I'm running into maximum recursion errors in comparison when I use Salesforce.query, .query_all, and .create. 

'sf' is defined as: 
sf = Salesforce(username=sf_username, password=sf_password, security_token=sf_security_token, domain='test')

and I've confirmed login by pulling my user name after. Is this something on my side, or something within simple-salesforce?

Traceback (most recent call last):
  File "/Users/tws/Desktop/SSASB3.py", line 230, in <module>
    query = "SELECT Id, Name FROM Account WHERE Name = account_name"
    sf.query_all(format_soql(query))
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/simple_salesforce/api.py", line 543, in query_all
    all_records = list(records)
                  ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/simple_salesforce/api.py", line 516, in query_all_iter
    result = self.query(query, include_deleted=include_deleted, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/simple_salesforce/api.py", line 467, in query
    result = self._call_salesforce('GET', url, name='query',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/simple_salesforce/api.py", line 616, in _call_salesforce
    return self._call_salesforce(method, url, name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/simple_salesforce/api.py", line 616, in _call_salesforce
    return self._call_salesforce(method, url, name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/simple_salesforce/api.py", line 616, in _call_salesforce
    return self._call_salesforce(method, url, name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 733 more times]
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/simple_salesforce/api.py", line 615, in _call_salesforce
    self._refresh_session()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/simple_salesforce/api.py", line 283, in _refresh_session
    self.session_id, self.sf_instance = self._salesforce_login_partial()
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/simple_salesforce/login.py", line 221, in SalesforceLogin
    return soap_login(soap_url, login_soap_request_body,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/simple_salesforce/login.py", line 227, in soap_login
    response = (session or requests).post(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connection.py", line 241, in request
    headers = headers.copy()
              ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/structures.py", line 77, in copy
    return CaseInsensitiveDict(self._store.values())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/structures.py", line 44, in __init__
    self.update(data, **kwargs)
  File "<frozen _collections_abc>", line 980, in update
  File "<frozen abc>", line 119, in __instancecheck__
RecursionError: maximum recursion depth exceeded in comparison

**Comment by oov-too** [comment]
It was on my side

**Comment by esmith1092** [comment]
@oov-too What was your issue? I am seeing the same error when running a .describe() but not when running a queryall().
